# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 149e37dc1aa09ec7d42eb7799a6b4f1893f970bbe3c3bb7f998b888ad506d25b24feb6ddf9e77f3394c60e1d594718085fb3c2be581e9fd034e94c34ef35322a

test:
  secret_key_base: fbe7e1603ebe6e3b974451a2b7c46cfde1504a95560bbf63c56fa731d5f817da73fe91b995baa428aa45d348a8014bba6f361092b8ef3e5f32620143b4183085

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
